services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./project:/project
    environment:
      - DB_HOST=database
      - DB_NAME=test_db
      - DB_USER=admin
      - DB_PASS=21Csxyzx
    depends_on:
      - database
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 21Csxyzx
    ports:
      - 5432:5432

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - 6379:6379

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A project worker --loglevel=info
    volumes:
      - ./project:/project
    environment:
      - DB_HOST=database
      - DB_NAME=test_db
      - DB_USER=admin
      - DB_PASS=21Csxyzx
    links:
      - redis
    depends_on:
      - redis
      - database
      - web-app


  celery-beat:
    build:
      context: .
    entrypoint: celery
    command: -A project beat --loglevel=info
    volumes:
      - ./project:/project
    links:
      - redis
    depends_on:
      - redis
      - database
      - web-app